apiVersion: v1
kind: Pod
metadata:
  name: pod-with-multiple-containers
spec:
  containers:
  - name: 1st
    image: nginx
  - name: 2nd
    image: debian

    # command: ["/bin/sh", "-c"]
    # args:
    #   - while true; do
    #       date