apiVersion: v1
kind: Pod
metadata:
  name: centos
spec:
  containers:
  - name: centos
    image: centos:7
    command: ["sleep" , "1000"]
    env:
    - name: BATCH
      value: "54"          # Numericals should be enclosed in quotes 
    - name: ENVIRONMENT
      value: dev 
    - name: MONGODB_URL 
      value: mongo.cc.com 
    - name: APP
      value: ecomm 
    